PRAGMA foreign_keys = ON;

CREATE TEMP TABLE SERVER_DROP_RATE (MULTIPLIER RealValue REAL);
INSERT INTO SERVER_DROP_RATE (MULTIPLIER) VALUES (5.0);

DROP TABLE IF EXISTS MOB_DROPS;
CREATE TEMP TABLE MOB_DROPS (
    ID                      UNSIGNED INT PRIMARY KEY
   ,NAME                    TEXT
   ,LEVEL                   UNSIGNED INT
   ,HP                      UNSIGNED INT
   ,BASE_EXP                UNSIGNED INT
   ,JOB_EXP                 UNSIGNED INT
   ,MVP_EXP                 UNSIGNED INT
   ,BOSS                    UNSIGNED TINYINT
   ,MVP_DROP_ID_1           UNSIGNED INT
   ,MVP_DROP_NAME_1         TEXT
   ,MVP_DROP_SELL_VALUE_1   UNSIGNED INT
   ,MVP_DROP_PERCENTAGE_1   REAL
   ,MVP_DROP_ID_2           UNSIGNED INT
   ,MVP_DROP_NAME_2         TEXT
   ,MVP_DROP_SELL_VALUE_2   UNSIGNED INT
   ,MVP_DROP_PERCENTAGE_2   REAL
   ,MVP_DROP_ID_3           UNSIGNED INT
   ,MVP_DROP_NAME_3         TEXT
   ,MVP_DROP_SELL_VALUE_3   UNSIGNED INT
   ,MVP_DROP_PERCENTAGE_3   REAL
   ,DROP_ID_1               UNSIGNED INT
   ,DROP_NAME_1             TEXT
   ,DROP_SELL_VALUE_1       UNSIGNED INT
   ,DROP_PERCENTAGE_1       REAL
   ,DROP_ID_2               UNSIGNED INT
   ,DROP_NAME_2             TEXT
   ,DROP_SELL_VALUE_2       UNSIGNED INT
   ,DROP_PERCENTAGE_2       REAL
   ,DROP_ID_3               UNSIGNED INT
   ,DROP_NAME_3             TEXT
   ,DROP_SELL_VALUE_3       UNSIGNED INT
   ,DROP_PERCENTAGE_3       REAL
   ,DROP_ID_4               UNSIGNED INT
   ,DROP_NAME_4             TEXT
   ,DROP_SELL_VALUE_4       UNSIGNED INT
   ,DROP_PERCENTAGE_4       REAL
   ,DROP_ID_5               UNSIGNED INT
   ,DROP_NAME_5             TEXT
   ,DROP_SELL_VALUE_5       UNSIGNED INT
   ,DROP_PERCENTAGE_5       REAL
   ,DROP_ID_6               UNSIGNED INT
   ,DROP_NAME_6             TEXT
   ,DROP_SELL_VALUE_6       UNSIGNED INT
   ,DROP_PERCENTAGE_6       REAL
   ,DROP_ID_7               UNSIGNED INT
   ,DROP_NAME_7             TEXT
   ,DROP_SELL_VALUE_7       UNSIGNED INT
   ,DROP_PERCENTAGE_7       REAL
   ,DROP_ID_8               UNSIGNED INT
   ,DROP_NAME_8             TEXT
   ,DROP_SELL_VALUE_8       UNSIGNED INT
   ,DROP_PERCENTAGE_8       REAL
   ,DROP_ID_9               UNSIGNED INT
   ,DROP_NAME_9             TEXT
   ,DROP_SELL_VALUE_9       UNSIGNED INT
   ,DROP_PERCENTAGE_9       REAL
   ,CARD_DROP_ID            UNSIGNED INT
   ,CARD_DROP_NAME          TEXT
   ,CARD_DROP_SELL_VALUE    UNSIGNED INT
   ,CARD_DROP_PERCENTAGE    REAL
);

INSERT INTO MOB_DROPS (
    ID
   ,NAME
   ,LEVEL
   ,HP
   ,BASE_EXP
   ,JOB_EXP
   ,MVP_EXP
   ,BOSS
   ,MVP_DROP_ID_1
   ,MVP_DROP_NAME_1
   ,MVP_DROP_SELL_VALUE_1
   ,MVP_DROP_PERCENTAGE_1
   ,MVP_DROP_ID_2
   ,MVP_DROP_NAME_2
   ,MVP_DROP_SELL_VALUE_2
   ,MVP_DROP_PERCENTAGE_2
   ,MVP_DROP_ID_3
   ,MVP_DROP_NAME_3
   ,MVP_DROP_SELL_VALUE_3
   ,MVP_DROP_PERCENTAGE_3
   ,DROP_ID_1
   ,DROP_NAME_1
   ,DROP_SELL_VALUE_1
   ,DROP_PERCENTAGE_1
   ,DROP_ID_2
   ,DROP_NAME_2
   ,DROP_SELL_VALUE_2
   ,DROP_PERCENTAGE_2
   ,DROP_ID_3
   ,DROP_NAME_3
   ,DROP_SELL_VALUE_3
   ,DROP_PERCENTAGE_3
   ,DROP_ID_4
   ,DROP_NAME_4
   ,DROP_SELL_VALUE_4
   ,DROP_PERCENTAGE_4
   ,DROP_ID_5
   ,DROP_NAME_5
   ,DROP_SELL_VALUE_5
   ,DROP_PERCENTAGE_5
   ,DROP_ID_6
   ,DROP_NAME_6
   ,DROP_SELL_VALUE_6
   ,DROP_PERCENTAGE_6
   ,DROP_ID_7
   ,DROP_NAME_7
   ,DROP_SELL_VALUE_7
   ,DROP_PERCENTAGE_7
   ,DROP_ID_8
   ,DROP_NAME_8
   ,DROP_SELL_VALUE_8
   ,DROP_PERCENTAGE_8
   ,DROP_ID_9
   ,DROP_NAME_9
   ,DROP_SELL_VALUE_9
   ,DROP_PERCENTAGE_9
   ,CARD_DROP_ID
   ,CARD_DROP_NAME
   ,CARD_DROP_SELL_VALUE
   ,CARD_DROP_PERCENTAGE
)
SELECT
    MOBS.ID
   ,MOBS.NAME
   ,MOBS.LEVEL
   ,MOBS.HP
   ,MOBS.BASE_EXP
   ,MOBS.JOB_EXP
   ,MOBS.MVP_EXP
   ,MOBS.BOSS

   ,MOBS.MVP_DROP_ID_1
   ,MVP_ITEM_1.NAME
   ,MVP_ITEM_1.SELL_PRICE
   ,CAST(MOBS.MVP_DROP_PERCENTAGE_1 AS REAL) / 100
   ,MOBS.MVP_DROP_ID_2
   ,MVP_ITEM_2.NAME
   ,MVP_ITEM_2.SELL_PRICE
   ,CAST(MOBS.MVP_DROP_PERCENTAGE_2 AS REAL) / 100
   ,MOBS.MVP_DROP_ID_3
   ,MVP_ITEM_3.NAME
   ,MVP_ITEM_3.SELL_PRICE
   ,CAST(MOBS.MVP_DROP_PERCENTAGE_3 AS REAL) / 100

   ,MOBS.DROP_ID_1
   ,ITEM_1.NAME
   ,ITEM_1.SELL_PRICE
   ,CAST(MOBS.DROP_PERCENTAGE_1 AS REAL) / 100
   ,MOBS.DROP_ID_2
   ,ITEM_2.NAME
   ,ITEM_2.SELL_PRICE
   ,CAST(MOBS.DROP_PERCENTAGE_2 AS REAL) / 100
   ,MOBS.DROP_ID_3
   ,ITEM_3.NAME
   ,ITEM_3.SELL_PRICE
   ,CAST(MOBS.DROP_PERCENTAGE_3 AS REAL) / 100
   ,MOBS.DROP_ID_4
   ,ITEM_4.NAME
   ,ITEM_4.SELL_PRICE
   ,CAST(MOBS.DROP_PERCENTAGE_4 AS REAL) / 100
   ,MOBS.DROP_ID_5
   ,ITEM_5.NAME
   ,ITEM_5.SELL_PRICE
   ,CAST(MOBS.DROP_PERCENTAGE_5 AS REAL) / 100
   ,MOBS.DROP_ID_6
   ,ITEM_6.NAME
   ,ITEM_6.SELL_PRICE
   ,CAST(MOBS.DROP_PERCENTAGE_6 AS REAL) / 100
   ,MOBS.DROP_ID_7
   ,ITEM_7.NAME
   ,ITEM_7.SELL_PRICE
   ,CAST(MOBS.DROP_PERCENTAGE_7 AS REAL) / 100
   ,MOBS.DROP_ID_8
   ,ITEM_8.NAME
   ,ITEM_8.SELL_PRICE
   ,CAST(MOBS.DROP_PERCENTAGE_8 AS REAL) / 100
   ,MOBS.DROP_ID_9
   ,ITEM_9.NAME
   ,ITEM_9.SELL_PRICE
   ,CAST(MOBS.DROP_PERCENTAGE_9 AS REAL) / 100

   ,MOBS.CARD_DROP_ID
   ,CARD.NAME
   ,CARD.SELL_PRICE
   ,CAST(MOBS.CARD_DROP_PERCENTAGE AS REAL) / 100
FROM
    MOBS
    LEFT JOIN ITEMS AS MVP_ITEM_1 ON MOBS.MVP_DROP_ID_1 = MVP_ITEM_1.ID
    LEFT JOIN ITEMS AS MVP_ITEM_2 ON MOBS.MVP_DROP_ID_2 = MVP_ITEM_2.ID
    LEFT JOIN ITEMS AS MVP_ITEM_3 ON MOBS.MVP_DROP_ID_3 = MVP_ITEM_3.ID
    LEFT JOIN ITEMS AS ITEM_1     ON MOBS.DROP_ID_1     = ITEM_1.ID
    LEFT JOIN ITEMS AS ITEM_2     ON MOBS.DROP_ID_2     = ITEM_2.ID
    LEFT JOIN ITEMS AS ITEM_3     ON MOBS.DROP_ID_3     = ITEM_3.ID
    LEFT JOIN ITEMS AS ITEM_4     ON MOBS.DROP_ID_4     = ITEM_4.ID
    LEFT JOIN ITEMS AS ITEM_5     ON MOBS.DROP_ID_5     = ITEM_5.ID
    LEFT JOIN ITEMS AS ITEM_6     ON MOBS.DROP_ID_6     = ITEM_6.ID
    LEFT JOIN ITEMS AS ITEM_7     ON MOBS.DROP_ID_7     = ITEM_7.ID
    LEFT JOIN ITEMS AS ITEM_8     ON MOBS.DROP_ID_8     = ITEM_8.ID
    LEFT JOIN ITEMS AS ITEM_9     ON MOBS.DROP_ID_9     = ITEM_9.ID
    LEFT JOIN ITEMS AS CARD       ON MOBS.CARD_DROP_ID  = CARD.ID
;

UPDATE
    MOB_DROPS
SET
    MVP_DROP_PERCENTAGE_1 = MVP_DROP_PERCENTAGE_1 * (SELECT MULTIPLIER FROM SERVER_DROP_RATE LIMIT 1)
   ,MVP_DROP_PERCENTAGE_2 = MVP_DROP_PERCENTAGE_2 * (SELECT MULTIPLIER FROM SERVER_DROP_RATE LIMIT 1)
   ,MVP_DROP_PERCENTAGE_3 = MVP_DROP_PERCENTAGE_3 * (SELECT MULTIPLIER FROM SERVER_DROP_RATE LIMIT 1)
   ,DROP_PERCENTAGE_1     = DROP_PERCENTAGE_1     * (SELECT MULTIPLIER FROM SERVER_DROP_RATE LIMIT 1)
   ,DROP_PERCENTAGE_2     = DROP_PERCENTAGE_2     * (SELECT MULTIPLIER FROM SERVER_DROP_RATE LIMIT 1)
   ,DROP_PERCENTAGE_3     = DROP_PERCENTAGE_3     * (SELECT MULTIPLIER FROM SERVER_DROP_RATE LIMIT 1)
   ,DROP_PERCENTAGE_4     = DROP_PERCENTAGE_4     * (SELECT MULTIPLIER FROM SERVER_DROP_RATE LIMIT 1)
   ,DROP_PERCENTAGE_5     = DROP_PERCENTAGE_5     * (SELECT MULTIPLIER FROM SERVER_DROP_RATE LIMIT 1)
   ,DROP_PERCENTAGE_6     = DROP_PERCENTAGE_6     * (SELECT MULTIPLIER FROM SERVER_DROP_RATE LIMIT 1)
   ,DROP_PERCENTAGE_7     = DROP_PERCENTAGE_7     * (SELECT MULTIPLIER FROM SERVER_DROP_RATE LIMIT 1)
   ,DROP_PERCENTAGE_8     = DROP_PERCENTAGE_8     * (SELECT MULTIPLIER FROM SERVER_DROP_RATE LIMIT 1)
   ,DROP_PERCENTAGE_9     = DROP_PERCENTAGE_9     * (SELECT MULTIPLIER FROM SERVER_DROP_RATE LIMIT 1)
   ,CARD_DROP_PERCENTAGE  = CARD_DROP_PERCENTAGE  * (SELECT MULTIPLIER FROM SERVER_DROP_RATE LIMIT 1)
;

UPDATE
    MOB_DROPS
SET
    MVP_DROP_PERCENTAGE_1 = IIF(MVP_DROP_PERCENTAGE_1 > 100, 100, MVP_DROP_PERCENTAGE_1)
   ,MVP_DROP_PERCENTAGE_2 = IIF(MVP_DROP_PERCENTAGE_2 > 100, 100, MVP_DROP_PERCENTAGE_2)
   ,MVP_DROP_PERCENTAGE_3 = IIF(MVP_DROP_PERCENTAGE_3 > 100, 100, MVP_DROP_PERCENTAGE_3)
   ,DROP_PERCENTAGE_1     = IIF(DROP_PERCENTAGE_1     > 100, 100, DROP_PERCENTAGE_1    )
   ,DROP_PERCENTAGE_2     = IIF(DROP_PERCENTAGE_2     > 100, 100, DROP_PERCENTAGE_2    )
   ,DROP_PERCENTAGE_3     = IIF(DROP_PERCENTAGE_3     > 100, 100, DROP_PERCENTAGE_3    )
   ,DROP_PERCENTAGE_4     = IIF(DROP_PERCENTAGE_4     > 100, 100, DROP_PERCENTAGE_4    )
   ,DROP_PERCENTAGE_5     = IIF(DROP_PERCENTAGE_5     > 100, 100, DROP_PERCENTAGE_5    )
   ,DROP_PERCENTAGE_6     = IIF(DROP_PERCENTAGE_6     > 100, 100, DROP_PERCENTAGE_6    )
   ,DROP_PERCENTAGE_7     = IIF(DROP_PERCENTAGE_7     > 100, 100, DROP_PERCENTAGE_7    )
   ,DROP_PERCENTAGE_8     = IIF(DROP_PERCENTAGE_8     > 100, 100, DROP_PERCENTAGE_8    )
   ,DROP_PERCENTAGE_9     = IIF(DROP_PERCENTAGE_9     > 100, 100, DROP_PERCENTAGE_9    )
   ,CARD_DROP_PERCENTAGE  = IIF(CARD_DROP_PERCENTAGE  > 100, 100, CARD_DROP_PERCENTAGE )
;

DROP TABLE IF EXISTS MOB_DROP_ANALYSIS_5X;
CREATE TABLE MOB_DROP_ANALYSIS_5X AS
SELECT
    ID
   ,NAME
   ,LEVEL
   ,HP
   ,BASE_EXP
   ,JOB_EXP
   ,MVP_EXP
   ,BOSS
   ,IFNULL(MVP_DROP_SELL_VALUE_1 * (MVP_DROP_PERCENTAGE_1 / 100), 0)
   +IFNULL(MVP_DROP_SELL_VALUE_2 * (MVP_DROP_PERCENTAGE_2 / 100), 0)
   +IFNULL(MVP_DROP_SELL_VALUE_3 * (MVP_DROP_PERCENTAGE_3 / 100), 0)
   +IFNULL(DROP_SELL_VALUE_1     * (DROP_PERCENTAGE_1     / 100), 0)
   +IFNULL(DROP_SELL_VALUE_2     * (DROP_PERCENTAGE_2     / 100), 0)
   +IFNULL(DROP_SELL_VALUE_3     * (DROP_PERCENTAGE_3     / 100), 0)
   +IFNULL(DROP_SELL_VALUE_4     * (DROP_PERCENTAGE_4     / 100), 0)
   +IFNULL(DROP_SELL_VALUE_5     * (DROP_PERCENTAGE_5     / 100), 0)
   +IFNULL(DROP_SELL_VALUE_6     * (DROP_PERCENTAGE_6     / 100), 0)
   +IFNULL(DROP_SELL_VALUE_7     * (DROP_PERCENTAGE_7     / 100), 0)
   +IFNULL(DROP_SELL_VALUE_8     * (DROP_PERCENTAGE_8     / 100), 0)
   +IFNULL(DROP_SELL_VALUE_9     * (DROP_PERCENTAGE_9     / 100), 0)
   +IFNULL(CARD_DROP_SELL_VALUE  * (CARD_DROP_PERCENTAGE  / 100), 0)
   AS EXPECTED_VALUE
   ,MVP_DROP_NAME_1
   ,MVP_DROP_SELL_VALUE_1
   ,MVP_DROP_PERCENTAGE_1
   ,MVP_DROP_NAME_2
   ,MVP_DROP_SELL_VALUE_2
   ,MVP_DROP_PERCENTAGE_2
   ,MVP_DROP_NAME_3
   ,MVP_DROP_SELL_VALUE_3
   ,MVP_DROP_PERCENTAGE_3
   ,DROP_NAME_1
   ,DROP_SELL_VALUE_1
   ,DROP_PERCENTAGE_1
   ,DROP_NAME_2
   ,DROP_SELL_VALUE_2
   ,DROP_PERCENTAGE_2
   ,DROP_NAME_3
   ,DROP_SELL_VALUE_3
   ,DROP_PERCENTAGE_3
   ,DROP_NAME_4
   ,DROP_SELL_VALUE_4
   ,DROP_PERCENTAGE_4
   ,DROP_NAME_5
   ,DROP_SELL_VALUE_5
   ,DROP_PERCENTAGE_5
   ,DROP_NAME_6
   ,DROP_SELL_VALUE_6
   ,DROP_PERCENTAGE_6
   ,DROP_NAME_7
   ,DROP_SELL_VALUE_7
   ,DROP_PERCENTAGE_7
   ,DROP_NAME_8
   ,DROP_SELL_VALUE_8
   ,DROP_PERCENTAGE_8
   ,DROP_NAME_9
   ,DROP_SELL_VALUE_9
   ,DROP_PERCENTAGE_9
   ,CARD_DROP_NAME
   ,CARD_DROP_SELL_VALUE
   ,CARD_DROP_PERCENTAGE
FROM
    MOB_DROPS
;
