PRAGMA foreign_keys = ON;

CREATE TEMP TABLE SERVER_DROP_RATE (MULTIPLIER RealValue REAL);
INSERT INTO SERVER_DROP_RATE (MULTIPLIER) VALUES (5.0);

DROP TABLE IF EXISTS MOB_DROPS;
CREATE TEMP TABLE MOB_DROPS (
    MOB_ID                  UNSIGNED INT
   ,MOB_NAME                TEXT
   ,MOB_LEVEL               UNSIGNED INT
   ,MOB_HP                  UNSIGNED INT
   ,MOB_BASE_EXP            UNSIGNED INT
   ,MOB_JOB_EXP             UNSIGNED INT
   ,MOB_MVP_EXP             UNSIGNED INT
   ,MOB_IS_MVP              UNSIGNED TINYINT
   ,MOB_IS_PLANT            UNSIGNED TINYINT
   ,DROP_TYPE               TEXT
   ,DROP_ID                 UNSIGNED INT
   ,DROP_NAME               TEXT
   ,DROP_WEIGHT             REAL
   ,DROP_SELL_VALUE         UNSIGNED INT
   ,DROP_PERCENTAGE         REAL
);

INSERT INTO MOB_DROPS (
    MOB_ID
   ,MOB_NAME
   ,MOB_LEVEL
   ,MOB_HP
   ,MOB_BASE_EXP
   ,MOB_JOB_EXP
   ,MOB_MVP_EXP
   ,MOB_IS_MVP
   ,MOB_IS_PLANT
   ,DROP_TYPE
   ,DROP_ID
   ,DROP_NAME
   ,DROP_WEIGHT
   ,DROP_SELL_VALUE
   ,DROP_PERCENTAGE
)
SELECT
    MOBS.ID
   ,MOBS.NAME
   ,MOBS.LEVEL
   ,MOBS.HP
   ,MOBS.BASE_EXP
   ,MOBS.JOB_EXP
   ,MOBS.MVP_EXP
   ,IIF(MOBS.MVP_EXP > 0,1,0) AS MOB_IS_MVP
   ,MOBS.PLANT

   ,'MVP_DROP_1' AS DROP_TYPE
   ,MOBS.MVP_DROP_ID_1
   ,ITEMS.NAME
   ,ITEMS.WEIGHT
   ,ITEMS.SELL_PRICE
   ,MOBS.MVP_DROP_PERCENTAGE_1
FROM
    MOBS
    LEFT JOIN ITEMS ON
        MOBS.MVP_DROP_ID_1 = ITEMS.ID

UNION ALL

SELECT
    MOBS.ID
   ,MOBS.NAME
   ,MOBS.LEVEL
   ,MOBS.HP
   ,MOBS.BASE_EXP
   ,MOBS.JOB_EXP
   ,MOBS.MVP_EXP
   ,IIF(MOBS.MVP_EXP > 0,1,0) AS MOB_IS_MVP
   ,MOBS.PLANT

   ,'MVP_DROP_2' AS DROP_TYPE
   ,MOBS.MVP_DROP_ID_2
   ,ITEMS.NAME
   ,ITEMS.WEIGHT
   ,ITEMS.SELL_PRICE
   ,MOBS.MVP_DROP_PERCENTAGE_2
FROM
    MOBS
    LEFT JOIN ITEMS ON
        MOBS.MVP_DROP_ID_2 = ITEMS.ID

UNION ALL

SELECT
    MOBS.ID
   ,MOBS.NAME
   ,MOBS.LEVEL
   ,MOBS.HP
   ,MOBS.BASE_EXP
   ,MOBS.JOB_EXP
   ,MOBS.MVP_EXP
   ,IIF(MOBS.MVP_EXP > 0,1,0) AS MOB_IS_MVP
   ,MOBS.PLANT

   ,'MVP_DROP_3' AS DROP_TYPE
   ,MOBS.MVP_DROP_ID_3
   ,ITEMS.NAME
   ,ITEMS.WEIGHT
   ,ITEMS.SELL_PRICE
   ,MOBS.MVP_DROP_PERCENTAGE_3
FROM
    MOBS
    LEFT JOIN ITEMS ON
        MOBS.MVP_DROP_ID_3 = ITEMS.ID

UNION ALL

SELECT
    MOBS.ID
   ,MOBS.NAME
   ,MOBS.LEVEL
   ,MOBS.HP
   ,MOBS.BASE_EXP
   ,MOBS.JOB_EXP
   ,MOBS.MVP_EXP
   ,IIF(MOBS.MVP_EXP > 0,1,0) AS MOB_IS_MVP
   ,MOBS.PLANT

   ,'DROP_1' AS DROP_TYPE
   ,MOBS.DROP_ID_1
   ,ITEMS.NAME
   ,ITEMS.WEIGHT
   ,ITEMS.SELL_PRICE
   ,MOBS.DROP_PERCENTAGE_1
FROM
    MOBS
    LEFT JOIN ITEMS ON
        MOBS.DROP_ID_1 = ITEMS.ID

UNION ALL

SELECT
    MOBS.ID
   ,MOBS.NAME
   ,MOBS.LEVEL
   ,MOBS.HP
   ,MOBS.BASE_EXP
   ,MOBS.JOB_EXP
   ,MOBS.MVP_EXP
   ,IIF(MOBS.MVP_EXP > 0,1,0) AS MOB_IS_MVP
   ,MOBS.PLANT

   ,'DROP_2' AS DROP_TYPE
   ,MOBS.DROP_ID_2
   ,ITEMS.NAME
   ,ITEMS.WEIGHT
   ,ITEMS.SELL_PRICE
   ,MOBS.DROP_PERCENTAGE_2
FROM
    MOBS
    LEFT JOIN ITEMS ON
        MOBS.DROP_ID_2 = ITEMS.ID

UNION ALL

SELECT
    MOBS.ID
   ,MOBS.NAME
   ,MOBS.LEVEL
   ,MOBS.HP
   ,MOBS.BASE_EXP
   ,MOBS.JOB_EXP
   ,MOBS.MVP_EXP
   ,IIF(MOBS.MVP_EXP > 0,1,0) AS MOB_IS_MVP
   ,MOBS.PLANT

   ,'DROP_3' AS DROP_TYPE
   ,MOBS.DROP_ID_3
   ,ITEMS.NAME
   ,ITEMS.WEIGHT
   ,ITEMS.SELL_PRICE
   ,MOBS.DROP_PERCENTAGE_3
FROM
    MOBS
    LEFT JOIN ITEMS ON
        MOBS.DROP_ID_3 = ITEMS.ID

UNION ALL

SELECT
    MOBS.ID
   ,MOBS.NAME
   ,MOBS.LEVEL
   ,MOBS.HP
   ,MOBS.BASE_EXP
   ,MOBS.JOB_EXP
   ,MOBS.MVP_EXP
   ,IIF(MOBS.MVP_EXP > 0,1,0) AS MOB_IS_MVP
   ,MOBS.PLANT

   ,'DROP_4' AS DROP_TYPE
   ,MOBS.DROP_ID_4
   ,ITEMS.NAME
   ,ITEMS.WEIGHT
   ,ITEMS.SELL_PRICE
   ,MOBS.DROP_PERCENTAGE_4
FROM
    MOBS
    LEFT JOIN ITEMS ON
        MOBS.DROP_ID_4 = ITEMS.ID

UNION ALL

SELECT
    MOBS.ID
   ,MOBS.NAME
   ,MOBS.LEVEL
   ,MOBS.HP
   ,MOBS.BASE_EXP
   ,MOBS.JOB_EXP
   ,MOBS.MVP_EXP
   ,IIF(MOBS.MVP_EXP > 0,1,0) AS MOB_IS_MVP
   ,MOBS.PLANT

   ,'DROP_5' AS DROP_TYPE
   ,MOBS.DROP_ID_5
   ,ITEMS.NAME
   ,ITEMS.WEIGHT
   ,ITEMS.SELL_PRICE
   ,MOBS.DROP_PERCENTAGE_5
FROM
    MOBS
    LEFT JOIN ITEMS ON
        MOBS.DROP_ID_5 = ITEMS.ID

UNION ALL

SELECT
    MOBS.ID
   ,MOBS.NAME
   ,MOBS.LEVEL
   ,MOBS.HP
   ,MOBS.BASE_EXP
   ,MOBS.JOB_EXP
   ,MOBS.MVP_EXP
   ,IIF(MOBS.MVP_EXP > 0,1,0) AS MOB_IS_MVP
   ,MOBS.PLANT

   ,'DROP_6' AS DROP_TYPE
   ,MOBS.DROP_ID_6
   ,ITEMS.NAME
   ,ITEMS.WEIGHT
   ,ITEMS.SELL_PRICE
   ,MOBS.DROP_PERCENTAGE_6
FROM
    MOBS
    LEFT JOIN ITEMS ON
        MOBS.DROP_ID_6 = ITEMS.ID

UNION ALL

SELECT
    MOBS.ID
   ,MOBS.NAME
   ,MOBS.LEVEL
   ,MOBS.HP
   ,MOBS.BASE_EXP
   ,MOBS.JOB_EXP
   ,MOBS.MVP_EXP
   ,IIF(MOBS.MVP_EXP > 0,1,0) AS MOB_IS_MVP
   ,MOBS.PLANT

   ,'DROP_7' AS DROP_TYPE
   ,MOBS.DROP_ID_7
   ,ITEMS.NAME
   ,ITEMS.WEIGHT
   ,ITEMS.SELL_PRICE
   ,MOBS.DROP_PERCENTAGE_7
FROM
    MOBS
    LEFT JOIN ITEMS ON
        MOBS.DROP_ID_7 = ITEMS.ID

UNION ALL

SELECT
    MOBS.ID
   ,MOBS.NAME
   ,MOBS.LEVEL
   ,MOBS.HP
   ,MOBS.BASE_EXP
   ,MOBS.JOB_EXP
   ,MOBS.MVP_EXP
   ,IIF(MOBS.MVP_EXP > 0,1,0) AS MOB_IS_MVP
   ,MOBS.PLANT

   ,'DROP_8' AS DROP_TYPE
   ,MOBS.DROP_ID_8
   ,ITEMS.NAME
   ,ITEMS.WEIGHT
   ,ITEMS.SELL_PRICE
   ,MOBS.DROP_PERCENTAGE_8
FROM
    MOBS
    LEFT JOIN ITEMS ON
        MOBS.DROP_ID_8 = ITEMS.ID

UNION ALL

SELECT
    MOBS.ID
   ,MOBS.NAME
   ,MOBS.LEVEL
   ,MOBS.HP
   ,MOBS.BASE_EXP
   ,MOBS.JOB_EXP
   ,MOBS.MVP_EXP
   ,IIF(MOBS.MVP_EXP > 0,1,0) AS MOB_IS_MVP
   ,MOBS.PLANT

   ,'DROP_9' AS DROP_TYPE
   ,MOBS.DROP_ID_9
   ,ITEMS.NAME
   ,ITEMS.WEIGHT
   ,ITEMS.SELL_PRICE
   ,MOBS.DROP_PERCENTAGE_9
FROM
    MOBS
    LEFT JOIN ITEMS ON
        MOBS.DROP_ID_9 = ITEMS.ID

UNION ALL

SELECT
    MOBS.ID
   ,MOBS.NAME
   ,MOBS.LEVEL
   ,MOBS.HP
   ,MOBS.BASE_EXP
   ,MOBS.JOB_EXP
   ,MOBS.MVP_EXP
   ,IIF(MOBS.MVP_EXP > 0,1,0) AS MOB_IS_MVP
   ,MOBS.PLANT

   ,'CARD_DROP' AS DROP_TYPE
   ,MOBS.CARD_DROP_ID
   ,ITEMS.NAME
   ,ITEMS.WEIGHT
   ,ITEMS.SELL_PRICE
   ,MOBS.CARD_DROP_PERCENTAGE
FROM
    MOBS
    LEFT JOIN ITEMS ON
        MOBS.CARD_DROP_ID = ITEMS.ID
;

UPDATE
    MOB_DROPS
SET
    DROP_PERCENTAGE = (DROP_PERCENTAGE/100) * (SELECT MULTIPLIER FROM SERVER_DROP_RATE LIMIT 1)
;

UPDATE
    MOB_DROPS
SET
    DROP_PERCENTAGE = IIF(DROP_PERCENTAGE > 100, 100, DROP_PERCENTAGE)
;

DROP TABLE IF EXISTS MOB_DROP_ANALYSIS_5X_V2;
CREATE TABLE MOB_DROP_ANALYSIS_5X_V2 AS
SELECT
    MOB_ID
   ,MOB_NAME
   ,MOB_LEVEL
   ,MOB_HP
   ,MOB_BASE_EXP
   ,MOB_JOB_EXP
   ,MOB_MVP_EXP
   ,MOB_IS_MVP
   ,MOB_IS_PLANT
   ,DROP_TYPE
   ,DROP_ID
   ,DROP_NAME
   ,DROP_WEIGHT
   ,DROP_SELL_VALUE
   ,DROP_PERCENTAGE
FROM
    MOB_DROPS
;
