PRAGMA foreign_keys = ON;

CREATE TEMP TABLE MOB_EXPECTED_VALUE AS
SELECT
    MOB_ID
   ,MOB_NAME
   ,MOB_LEVEL
   ,MOB_HP
   ,MOB_BASE_EXP
   ,MOB_JOB_EXP
   ,MOB_MVP_EXP
   ,MOB_IS_MVP
   ,MOB_IS_PLANT
   ,SUM(1.0 * DROP_SELL_VALUE * (DROP_PERCENTAGE / 100))               AS EXPECTED_VALUE
   ,SUM(1.0 * DROP_SELL_VALUE * (DROP_PERCENTAGE / 100) / DROP_WEIGHT) AS VALUE_WEIGHT_EFFICIENCY
   ,SUM(1.0 * DROP_SELL_VALUE * (DROP_PERCENTAGE / 100) / MOB_HP)      AS VALUE_HP_EFFICIENCY
   ,SUM(1.0 * DROP_SELL_VALUE * (DROP_PERCENTAGE / 100) / MOB_LEVEL)   AS VALUE_LVL_EFFICIENCY
FROM
    MOB_DROP_ANALYSIS_5X_V2
GROUP BY
    MOB_ID
;

CREATE TEMP TABLE MAP_SPAWNS AS
SELECT
    MAP_NAME
   ,MOB_ID
   ,AMOUNT
   ,1.0*AMOUNT/SUM(AMOUNT) OVER (PARTITION BY MAP_NAME) AS CONCENTRATION
   ,SUM(AMOUNT) OVER (PARTITION BY MAP_NAME) AS TOTAL_AMOUNT
FROM
    MOBS_ON_MAP
;

SELECT
    MAP.MAP_NAME
--    ,MOB.MOB_NAME
--    ,MOB.EXPECTED_VALUE
   ,SUM(MOB.EXPECTED_VALUE*MAP.CONCENTRATION)
--    OVER (PARTITION BY MAP_NAME)
   AS RANDOM_KILL_VALUE
   ,CAST(AVG(MOB.MOB_LEVEL) AS INT) AS AVERAGE_MOB_LEVEL
--    ,MAP.CONCENTRATION
--    ,MOB.EXPECTED_VALUE*MAP.CONCENTRATION AS RANDOM_KILL_VALUE
FROM
    MAP_SPAWNS AS MAP
LEFT JOIN
    MOB_EXPECTED_VALUE AS MOB
        ON MAP.MOB_ID = MOB.MOB_ID
WHERE
        MOB_IS_PLANT = 0
    AND MOB_IS_MVP = 0
    AND MOB_NAME != 'Treasure Chest'
GROUP BY
    MAP.MAP_NAME
ORDER BY
    RANDOM_KILL_VALUE DESC
;


SELECT
    MOB.MOB_ID
   ,MOB.MOB_NAME
   ,EFF.EXPECTED_VALUE
   ,MOB.DROP_NAME
   ,MOB.DROP_SELL_VALUE AS VALUE
   ,MOB.DROP_WEIGHT / 10 AS WEIGHT
   ,MOB.DROP_SELL_VALUE*MOB.DROP_PERCENTAGE/100 AS EXPECTED_DROP_VALUE
   ,MOB.DROP_SELL_VALUE/(MOB.DROP_WEIGHT/10) AS WEIGHT_EFFICIENCY
FROM
    MOB_DROP_ANALYSIS_5X_V2 AS MOB
LEFT JOIN
    MOBS_ON_MAP AS MAP ON
        MAP.MOB_ID = MOB.MOB_ID
LEFT JOIN
    MOB_EXPECTED_VALUE AS EFF ON
        EFF.MOB_ID = MOB.MOB_ID
WHERE
        MAP.MAP_NAME = 'yuno_fild02'
    AND MOB.MOB_IS_PLANT = 0
    AND MOB.MOB_IS_MVP = 0
    AND MOB.DROP_ID != 0
ORDER BY
    EXPECTED_DROP_VALUE DESC
;