PRAGMA foreign_keys = ON;

DROP TABLE IF EXISTS MOBS_ON_MAP;
DROP TABLE IF EXISTS MOBS;
DROP TABLE IF EXISTS ITEMS;
DROP TABLE IF EXISTS ITEM_CLASSES;

CREATE TABLE IF NOT EXISTS ITEM_CLASSES (
    ID   UNSIGNED INT PRIMARY KEY
   ,NAME TEXT
);

INSERT INTO ITEM_CLASSES
    (ID, NAME)
VALUES
    (0, 'Healing Item')
   ,(2, 'Special Usable Item')
   ,(3, 'Misc')
   ,(4, 'Shield')
   ,(5, 'Sword')
   ,(6, 'Card')
   ,(7, 'Egg')
   ,(8, 'Headwear')
   ,(10, 'Ammunition')
   ,(11, 'Also Usable')
   ,(12, 'Shadow Gear')
   ,(18, 'Boxes')
   ,(522, 'HEALING ITEMS')
;

CREATE TABLE IF NOT EXISTS ITEMS (
    ID         UNSIGNED INT PRIMARY KEY
   ,NAME       TEXT
   ,CLASS_ID   UNSIGNED INT REFERENCES ITEM_CLASSES(ID)
   ,WEIGHT     UNSIGNED INT
   ,BUY_PRICE  UNSIGNED INT
   ,SELL_PRICE UNSIGNED INT
);

CREATE TABLE IF NOT EXISTS MOBS (
    ID                      UNSIGNED INT PRIMARY KEY
   ,NAME                    TEXT
   ,LEVEL                   UNSIGNED INT
   ,HP                      UNSIGNED INT
   ,BASE_EXP                UNSIGNED INT
   ,JOB_EXP                 UNSIGNED INT
   ,CAN_MOVE                UNSIGNED TINYINT
   ,LOOTER                  UNSIGNED TINYINT
   ,AGRESSIVE               UNSIGNED TINYINT
   ,ASSIST                  UNSIGNED TINYINT
   ,CAST_SENSOR_IDLE        UNSIGNED TINYINT
   ,BOSS                    UNSIGNED TINYINT
   ,PLANT                   UNSIGNED TINYINT
   ,CAN_ATTACK              UNSIGNED TINYINT
   ,CHANGE_CHASE            UNSIGNED TINYINT
   ,ANGRY                   UNSIGNED TINYINT
   ,CHANGE_TARGET_MELEE     UNSIGNED TINYINT
   ,CHANGE_TARGET_CHASE     UNSIGNED TINYINT
   ,TARGET_WEAK             UNSIGNED TINYINT
   ,NO_KNOCKBACK            UNSIGNED TINYINT
   ,MOVE_SPEED              UNSIGNED INT
   ,ATTACK_DELAY            UNSIGNED INT
   ,MVP_EXP                 UNSIGNED INT
   ,MVP_DROP_ID_1           UNSIGNED INT REFERENCES ITEMS(ID)
   ,MVP_DROP_PERCENTAGE_1   UNSIGNED INT
   ,MVP_DROP_ID_2           UNSIGNED INT REFERENCES ITEMS(ID)
   ,MVP_DROP_PERCENTAGE_2   UNSIGNED INT
   ,MVP_DROP_ID_3           UNSIGNED INT REFERENCES ITEMS(ID)
   ,MVP_DROP_PERCENTAGE_3   UNSIGNED INT
   ,DROP_ID_1               UNSIGNED INT REFERENCES ITEMS(ID)
   ,DROP_PERCENTAGE_1       UNSIGNED INT
   ,DROP_ID_2               UNSIGNED INT REFERENCES ITEMS(ID)
   ,DROP_PERCENTAGE_2       UNSIGNED INT
   ,DROP_ID_3               UNSIGNED INT REFERENCES ITEMS(ID)
   ,DROP_PERCENTAGE_3       UNSIGNED INT
   ,DROP_ID_4               UNSIGNED INT REFERENCES ITEMS(ID)
   ,DROP_PERCENTAGE_4       UNSIGNED INT
   ,DROP_ID_5               UNSIGNED INT REFERENCES ITEMS(ID)
   ,DROP_PERCENTAGE_5       UNSIGNED INT
   ,DROP_ID_6               UNSIGNED INT REFERENCES ITEMS(ID)
   ,DROP_PERCENTAGE_6       UNSIGNED INT
   ,DROP_ID_7               UNSIGNED INT REFERENCES ITEMS(ID)
   ,DROP_PERCENTAGE_7       UNSIGNED INT
   ,DROP_ID_8               UNSIGNED INT REFERENCES ITEMS(ID)
   ,DROP_PERCENTAGE_8       UNSIGNED INT
   ,DROP_ID_9               UNSIGNED INT REFERENCES ITEMS(ID)
   ,DROP_PERCENTAGE_9       UNSIGNED INT
   ,CARD_DROP_ID            UNSIGNED INT REFERENCES ITEMS(ID)
   ,CARD_DROP_PERCENTAGE    UNSIGNED INT
);

CREATE TABLE IF NOT EXISTS MOBS_ON_MAP (
    MOB_ID                  UNSIGNED INT REFERENCES MOBS(ID)
   ,MAP_NAME                TEXT
   ,AMOUNT                  UNSIGNED INT
);